--Drop User_Account table

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USER_ACCOUNT CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


--Drop Team_Owner Table

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TEAM_OWNER CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


--Drop Team Table

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TEAM CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

--Drop Venue Table

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE VENUE CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


--Drop Player Table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PLAYER CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

--Drop Bid Table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BID CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

--Drop League Table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LEAGUE CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

--Drop Fixture Table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FIXTURE CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


--Drop Payment Table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PAYMENT CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


--Drop Ticket_Class Table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TICKET_CLASS CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


--Drop Booking Table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BOOKING CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


--Drop Audience Table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AUDIENCE CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


--Drop Team_Standings Table
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TEAM_STANDINGS CASCADE CONSTRAINTS' ;
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


--User_Account Table Creation
CREATE TABLE USER_ACCOUNT(
USER_ID NUMBER(10) NOT NULL,
USER_TYPE VARCHAR(10) NOT NULL,
USERNAME VARCHAR(20) NOT NULL,
USER_PWD VARCHAR(20),
AGE NUMBER(2),
SEX VARCHAR(10),
EMAIL VARCHAR(30),
CONTACT NUMBER(10),
CONSTRAINT USER_ACCOUNT_PK PRIMARY KEY(USER_ID));


--Team_Owner Table Creation
CREATE TABLE TEAM_OWNER(
Owner_Id NUMBER(10) NOT NULL,
User_Id NUMBER(10) NOT NULL,
Owner_Name VARCHAR2(30)NOT NULL ,
Team_Name VARCHAR2(30) NOT NULL,
Alloted_Amount NUMBER(30),
CONSTRAINT TEAM_OWNER_PK PRIMARY KEY(Owner_Id));


--Team Table Creation
CREATE TABLE TEAM(
Team_Id VARCHAR2(5) NOT NULL,
Owner_Id NUMBER(10) NOT NULL,
Team_Name VARCHAR2(30) NOT NULL,
Home_Ground VARCHAR2(30),
CONSTRAINT TEAM_PK PRIMARY KEY(Team_Id));

--Venue Table Creation
CREATE TABLE VENUE(
VENUE_ID NUMBER(5) NOT NULL,
VENUE_NAME VARCHAR(30) NOT NULL,
VENUE_STANDS NUMBER(2)NOT NULL,
VENUE_CAPACITY NUMBER(6) NOT NULL,
HOME_TEAM_ID VARCHAR2(5) NOT NULL,
CITY VARCHAR(20),
CONSTRAINT VENUE_PK PRIMARY KEY(VENUE_ID));

--Playe Table Creation
CREATE TABLE PLAYER (
Player_ID NUMBER NOT NULL,
User_ID NUMBER NOT NULL,
Team_ID VARCHAR2(5) NOT NULL,
Player_Name VARCHAR(20) NOT NULL,
Base_Price NUMBER DEFAULT 50000,
Player_Type VARCHAR(20) NOT NULL,
Player_Role VARCHAR(20) NOT NULL,
Country VARCHAR(20) NOT NULL ,
Constraint PLAYER_PK PRIMARY KEY(Player_ID));


--Bid Table Creation
 CREATE TABLE BID(
BID_ID NUMBER(10) NOT NULL,
OWNER_ID NUMBER(10) NOT NULL,
PLAYER_ID NUMBER(10) NOT NULL,
BID_TIME DATE,
IS_FINAL_BID CHAR(1),
BID_AMOUNT NUMBER(10),
LEAGUE_ID NUMBER(10),
CONSTRAINT BID_PK PRIMARY KEY(BID_ID));
 
 
--League Table Creation
CREATE TABLE LEAGUE(
LEAGUE_ID NUMBER(3) NOT NULL,
LEAGUE_NAME VARCHAR(30) NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
TEAM_COUNT NUMBER(2),
TOTAL_NUMBER_OF_MATCHES NUMBER(3),
CONSTRAINT LEAGUE_PK PRIMARY KEY(LEAGUE_ID));


--Fixture Table Creation
CREATE TABLE FIXTURE(
MATCH_ID NUMBER(5) NOT NULL,
TEAM1_ID VARCHAR2(5) NOT NULL,
TEAM2_ID VARCHAR2(5) NOT NULL,
VENUE_ID NUMBER(5) NOT NULL,
MATCH_DATE DATE NOT NULL,
WINNER VARCHAR2(5) NOT NULL,
WIN_DETAILS VARCHAR(20) NOT NULL,
LEAGUE_ID NUMBER(5) NOT NULL,
CONSTRAINT FIXTURE_PK PRIMARY KEY(MATCH_ID));
 
--Payment Table Creation
CREATE TABLE PAYMENT(
PAYMENT_ID NUMBER(5) NOT NULL,
BID_ID NUMBER(10) NOT NULL,
PLAYER_ID NUMBER NOT NULL,
REFERENCE_NUM NUMBER(10) NOT NULL,
CONSTRAINT PAYMENT_PK PRIMARY KEY(PAYMENT_ID));

--Ticket_Class Table Creation
CREATE TABLE TICKET_CLASS(
TICKET_ID NUMBER(10) NOT NULL,
TICKET_TYPE VARCHAR(10),
TICKET_PRICE NUMBER(5),
CONSTRAINT TICKET_CLASS_PK PRIMARY KEY(TICKET_ID));
 
--Booking Table Creation
CREATE TABLE BOOKING(
BOOKING_ID NUMBER(10) NOT NULL,
MATCH_ID NUMBER(10) NOT NULL,
TICKET_TYPE_ID NUMBER(10) NOT NULL,
AUDIENCE_ID NUMBER(10) NOT NULL,
TICKET_COUNT NUMBER(10),
LEAGUE_ID NUMBER(5),
CONSTRAINT BOOKING_PK PRIMARY KEY(BOOKING_ID));

--Team_Standings Table Creation
CREATE TABLE TEAM_STANDINGS(
TEAM_STANDINGS_ID NUMBER NOT NULL,
TOTAL_MATCHES NUMBER,
MATCHES_WON NUMBER,
MATCHES_LOST NUMBER,
MATCHES_TIED NUMBER,
NO_RESULT NUMBER,
POINTS NUMBER,
LEAGUE_ID NUMBER(5) NOT NULL,
TEAM_ID VARCHAR2(5) NOT NULL,
CONSTRAINT TEAM_STANDINGS_PK PRIMARY KEY(TEAM_STANDINGS_ID));
 
--Audience Table Creation
CREATE TABLE AUDIENCE(
AUDIENCE_ID NUMBER(10) NOT NULL,
USER_ID NUMBER(10) NOT NULL,
AUDIENCE_NAME VARCHAR2(20),
CONSTRAINT AUDIENCE_PK PRIMARY KEY(AUDIENCE_ID));

--Add Foreign Key to Venue Table
ALTER TABLE VENUE
ADD CONSTRAINT fk_homeTeam_id_in_venuetbl
FOREIGN KEY(HOME_TEAM_ID)
REFERENCES TEAM(TEAM_ID);

--Add Foreign Key to Player Table
ALTER TABLE PLAYER
ADD CONSTRAINT fk_user_id_in_playertbl
FOREIGN KEY(USER_ID)
REFERENCES USER_ACCOUNT(USER_ID);


ALTER TABLE PLAYER
ADD CONSTRAINT fk_team_id_in_playertbl
FOREIGN KEY(team_id)
REFERENCES TEAM(team_id);
 
--Add Foreign Key to Bid Table
ALTER TABLE BID
ADD CONSTRAINT fk_owner_id_in_bidtbl
FOREIGN KEY(OWNER_ID)
REFERENCES TEAM_OWNER(OWNER_ID);

 
ALTER TABLE BID
ADD CONSTRAINT fk_player_id_in_bidtbl
FOREIGN KEY(PLAYER_ID)
REFERENCES PLAYER(PLAYER_ID);
 
--Add Foreign Key to Payment Table
ALTER TABLE PAYMENT
ADD CONSTRAINT fk_bid_id_in_paymenttbl
FOREIGN KEY(BID_ID)
REFERENCES BID(BID_ID);
 
 
ALTER TABLE PAYMENT
ADD CONSTRAINT fk_player_id_in_paymenttbl
FOREIGN KEY(PLAYER_ID)
REFERENCES PLAYER(PLAYER_ID);
 
--Add Foreign Key to Team Table
ALTER TABLE TEAM
ADD CONSTRAINT fk_owner_id_in_teamtbl
FOREIGN KEY(OWNER_ID)
REFERENCES TEAM_OWNER(OWNER_ID);
 
--Add Foreign Key to Team_Standings Table
ALTER TABLE TEAM_STANDINGS
ADD CONSTRAINT fk_league_id_in_teamstandingstbl
FOREIGN KEY(LEAGUE_ID)
REFERENCES LEAGUE(LEAGUE_ID);
 
--Add Foreign Key to Fixture Table 
ALTER TABLE FIXTURE
ADD CONSTRAINT fk_team1_id_matchtbl
FOREIGN KEY(TEAM1_ID)
REFERENCES TEAM(TEAM_ID);
 
ALTER TABLE FIXTURE
ADD CONSTRAINT fk_team2_id_matchtbl
FOREIGN KEY(TEAM2_ID)
REFERENCES TEAM(TEAM_ID);
 
 
ALTER TABLE FIXTURE
ADD CONSTRAINT fk_venue_id_matchtbl
FOREIGN KEY(VENUE_ID)
REFERENCES VENUE(VENUE_ID);

--Add Foreign Key to Audience Table
ALTER TABLE AUDIENCE
ADD CONSTRAINT fk_user_id_audiencetbl
FOREIGN KEY(USER_ID)
REFERENCES USER_ACCOUNT(USER_ID);

--Add Foreign Key to Booking Table
ALTER TABLE BOOKING
ADD CONSTRAINT fk_match_id_bookingtbl
FOREIGN KEY(MATCH_ID)
REFERENCES FIXTURE(MATCH_ID);
 
 
ALTER TABLE BOOKING
ADD CONSTRAINT fk_tickettype_id_bookingtbl
FOREIGN KEY(TICKET_TYPE_ID)
REFERENCES TICKET_CLASS(TICKET_ID);
 
ALTER TABLE BOOKING
ADD CONSTRAINT fk_audience_id_bookingtbl
FOREIGN KEY(AUDIENCE_ID)
REFERENCES AUDIENCE(AUDIENCE_ID);
 
--Add Unique Constraints
ALTER TABLE TEAM
ADD CONSTRAINT UNIQUE_TEAM_NAME
UNIQUE (TEAM_NAME);
 
ALTER TABLE VENUE
ADD CONSTRAINT UNIQUE_VENUE_NAME
UNIQUE (VENUE_NAME);
 
ALTER TABLE USER_ACCOUNT
ADD CONSTRAINT UNIQUE_USER_NAME
UNIQUE (USERNAME);
 
 
ALTER TABLE LEAGUE
ADD CONSTRAINT LEAGUE_NAME
UNIQUE (LEAGUE_NAME);
 
 
ALTER TABLE TEAM_OWNER
ADD CONSTRAINT OWNER_NAME
UNIQUE (OWNER_NAME);
 
 
ALTER TABLE PAYMENT
ADD CONSTRAINT REFERENCE_NUM
UNIQUE (REFERENCE_NUM);
 
ALTER TABLE PLAYER
ADD CONSTRAINT PLAYER_NAME
UNIQUE (PLAYER_NAME);
 
--Add Foreign Key to Fixture Table
ALTER TABLE FIXTURE
ADD CONSTRAINT fk_league_id_matchtbl
FOREIGN KEY(league_id)
REFERENCES LEAGUE(league_id);
 
--Add Foreign Key to Bid Table  
ALTER TABLE BID
ADD CONSTRAINT fk_league_id_fixturetbl
FOREIGN KEY(league_id)
REFERENCES LEAGUE(league_id);

--Add Check constraint to Booking Table
ALTER TABLE booking
ADD CONSTRAINT check_no_of_tickets
CHECK (ticket_count < 20);

--Alter data type of League_Id in league Table
ALTER TABLE LEAGUE
MODIFY LEAGUE_ID NUMBER(5);
