--Revenue generated by each match in the league

select ma.match_id as match_id, te1.team_name ||' vs '|| te2.team_name as teams, SUM(bk.ticket_count*tc.ticket_price) as revenue from ADMIN.fixture ma
inner join ADMIN.booking bk on bk.match_id = ma.match_id
inner join ADMIN.ticket_class tc on bk.ticket_type_id = tc.ticket_id
inner join ADMIN.team te1 on ma.team1_id = te1.team_id
inner join ADMIN.team te2 on ma.team2_id = te2.team_id
group by ma.match_id, te1.team_name, te2.team_name
order by revenue desc;

--top 10 most expensive players in league

select pl.player_name, pl.base_price, bid.bid_amount, ow.team_name as bought_by from ADMIN.bid bid
inner join ADMIN.team_owner ow on ow.owner_id=bid.owner_id
inner join ADMIN.player pl on pl.player_id=bid.player_id
where bid.is_final_bid='T'
order by bid.bid_amount desc
fetch first 10 rows only;

--Number of players in each team, domestic or international, batsman vs bowler vs wk

select te.team_name, SUM(CASE WHEN pl.player_role='BATSMAN' THEN 1 ELSE 0 END) AS Batsman,  
SUM(CASE WHEN pl.player_role = 'BOWLER' THEN 1 ELSE 0 END) AS Bowler, 
SUM(CASE WHEN pl.player_role = 'WK' THEN 1 ELSE 0 END) AS WK, 
SUM(CASE WHEN pl.player_role = 'ALLROUNDER' THEN 1 ELSE 0 END) AS AllRounder,
SUM(CASE WHEN pl.player_type = 'DOMESTIC' THEN 1 ELSE 0 END) AS Domestic,
SUM(CASE WHEN pl.player_type = 'INTERNATIONAL' THEN 1 ELSE 0 END) AS International
from admin.player pl
inner join admin.team te on te.team_id=pl.team_id
group by te.team_name;


--Reports to show the money spent, remaining money with each owner after bidding

select ow.team_name, round(SUM(bid.bid_amount)/10000000,2) as amount_spent, round(50 - SUM(bid.bid_amount)/10000000,2) as purse_left from admin.bid bid
inner join admin.team_owner ow on ow.owner_id=bid.owner_id
where bid.is_final_bid='T'
group by ow.team_name;


--Each team and owner with their highest bid amount in the league

select ow.team_name, ow.owner_name, max(bid.bid_amount) as max_bid from admin.team_owner ow
left join admin.bid bid on bid.owner_id=ow.owner_id
where bid.is_final_bid='T'
group by ow.team_name, ow.owner_name;